<?php

namespace AppBundle\Repository;

/**
 * QIbanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QIbanRepository extends \Doctrine\ORM\EntityRepository
{
}
