<?php

namespace AppBundle\Repository;

/**
 * QMainOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QMainOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
