<?php

namespace AppBundle\Repository;

/**
 * QOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
