<?php

namespace AppBundle\Repository;

/**
 * QProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QProductRepository extends \Doctrine\ORM\EntityRepository
{
}
