# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    sk_key: "%stripe_secret_key%"
    pk_key: "%stripe_publishable_key%"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.cart:
        class: AppBundle\Cart\Cart